# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170308_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='exif',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='images',
            name='misr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='images',
            name='results',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='images',
            name='wunder',
            field=models.CharField(max_length=200),
        ),
    ]
