# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170308_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.FileField(default='none', upload_to='../../../installDir/aerolyzerImgs'),
        ),
    ]
