# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
